name: LordTags
main: me.ShanaChans.LordTags.TagManager
author: [ShanaChans, Neoblade298]
depend: [NeoCore]
version: 1.0
api-version: 1.16
commands:
   tags:
      description: See all your tags!
      usage: /tags
   